server:
  port: 8088
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ego-order
    username: root
    password: root
  jackson:
    default-property-inclusion: non_null
mybatis-plus:
  mapper-locations: /mappers/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
